//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.01 at 09:17:57 AM CST 
//


package com.yuan.gui.app.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for build complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="build">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="hostip" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="promt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="user" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="pwd" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="svnUser" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="svnPwd" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="codepath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="svnpath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="winrarpath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="beid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="hostIpList" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="codePathList" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="svnPathList" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "build", propOrder = {
    "hostip",
    "promt",
    "user",
    "pwd",
    "svnUser",
    "svnPwd",
    "codepath",
    "svnpath",
    "winrarpath",
    "beid",
    "hostIpList",
    "codePathList",
    "svnPathList"
})
public class Build {

    @XmlElement(required = true)
    protected String hostip;
    @XmlElement(required = true)
    protected String promt;
    @XmlElement(required = true)
    protected String user;
    @XmlElement(required = true)
    protected String pwd;
    @XmlElement(required = true)
    protected String svnUser;
    @XmlElement(required = true)
    protected String svnPwd;
    @XmlElement(required = true)
    protected String codepath;
    @XmlElement(required = true)
    protected String svnpath;
    @XmlElement(required = true)
    protected String winrarpath;
    @XmlElement(required = true)
    protected String beid;
    protected List<String> hostIpList;
    protected List<String> codePathList;
    protected List<String> svnPathList;

    /**
     * Gets the value of the hostip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHostip() {
        return hostip;
    }

    /**
     * Sets the value of the hostip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHostip(String value) {
        this.hostip = value;
    }

    /**
     * Gets the value of the promt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPromt() {
        return promt;
    }

    /**
     * Sets the value of the promt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPromt(String value) {
        this.promt = value;
    }

    /**
     * Gets the value of the user property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUser() {
        return user;
    }

    /**
     * Sets the value of the user property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUser(String value) {
        this.user = value;
    }

    /**
     * Gets the value of the pwd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * Sets the value of the pwd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPwd(String value) {
        this.pwd = value;
    }

    /**
     * Gets the value of the svnUser property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSvnUser() {
        return svnUser;
    }

    /**
     * Sets the value of the svnUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSvnUser(String value) {
        this.svnUser = value;
    }

    /**
     * Gets the value of the svnPwd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSvnPwd() {
        return svnPwd;
    }

    /**
     * Sets the value of the svnPwd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSvnPwd(String value) {
        this.svnPwd = value;
    }

    /**
     * Gets the value of the codepath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodepath() {
        return codepath;
    }

    /**
     * Sets the value of the codepath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodepath(String value) {
        this.codepath = value;
    }

    /**
     * Gets the value of the svnpath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSvnpath() {
        return svnpath;
    }

    /**
     * Sets the value of the svnpath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSvnpath(String value) {
        this.svnpath = value;
    }

    /**
     * Gets the value of the winrarpath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWinrarpath() {
        return winrarpath;
    }

    /**
     * Sets the value of the winrarpath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWinrarpath(String value) {
        this.winrarpath = value;
    }

    /**
     * Gets the value of the beid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBeid() {
        return beid;
    }

    /**
     * Sets the value of the beid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBeid(String value) {
        this.beid = value;
    }

    /**
     * Gets the value of the hostIpList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hostIpList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHostIpList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getHostIpList() {
        if (hostIpList == null) {
            hostIpList = new ArrayList<String>();
        }
        return this.hostIpList;
    }

    /**
     * Gets the value of the codePathList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the codePathList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCodePathList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getCodePathList() {
        if (codePathList == null) {
            codePathList = new ArrayList<String>();
        }
        return this.codePathList;
    }

    /**
     * Gets the value of the svnPathList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the svnPathList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSvnPathList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getSvnPathList() {
        if (svnPathList == null) {
            svnPathList = new ArrayList<String>();
        }
        return this.svnPathList;
    }

}
