//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.01 at 09:17:57 AM CST 
//


package com.yuan.gui.app.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="settings" type="{http://www.example.org/config}settings" minOccurs="0"/>
 *         &lt;element name="xml2xsd" type="{http://www.example.org/config}xml2xsd" minOccurs="0"/>
 *         &lt;element name="xsd2java" type="{http://www.example.org/config}xsd2java" minOccurs="0"/>
 *         &lt;element name="xmlformat" type="{http://www.example.org/config}xmlformat" minOccurs="0"/>
 *         &lt;element name="build" type="{http://www.example.org/config}build" minOccurs="0"/>
 *         &lt;element name="javaformat" type="{http://www.example.org/config}javaformat" minOccurs="0"/>
 *         &lt;element name="exportCommitLog" type="{http://www.example.org/config}exportCommitLog" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "settings",
    "xml2Xsd",
    "xsd2Java",
    "xmlformat",
    "build",
    "javaformat",
    "exportCommitLog"
})
@XmlRootElement(name = "config")
public class Config {

    protected Settings settings;
    @XmlElement(name = "xml2xsd")
    protected Xml2Xsd xml2Xsd;
    @XmlElement(name = "xsd2java")
    protected Xsd2Java xsd2Java;
    protected Xmlformat xmlformat;
    protected Build build;
    protected Javaformat javaformat;
    protected ExportCommitLog exportCommitLog;

    /**
     * Gets the value of the settings property.
     * 
     * @return
     *     possible object is
     *     {@link Settings }
     *     
     */
    public Settings getSettings() {
        return settings;
    }

    /**
     * Sets the value of the settings property.
     * 
     * @param value
     *     allowed object is
     *     {@link Settings }
     *     
     */
    public void setSettings(Settings value) {
        this.settings = value;
    }

    /**
     * Gets the value of the xml2Xsd property.
     * 
     * @return
     *     possible object is
     *     {@link Xml2Xsd }
     *     
     */
    public Xml2Xsd getXml2Xsd() {
        return xml2Xsd;
    }

    /**
     * Sets the value of the xml2Xsd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Xml2Xsd }
     *     
     */
    public void setXml2Xsd(Xml2Xsd value) {
        this.xml2Xsd = value;
    }

    /**
     * Gets the value of the xsd2Java property.
     * 
     * @return
     *     possible object is
     *     {@link Xsd2Java }
     *     
     */
    public Xsd2Java getXsd2Java() {
        return xsd2Java;
    }

    /**
     * Sets the value of the xsd2Java property.
     * 
     * @param value
     *     allowed object is
     *     {@link Xsd2Java }
     *     
     */
    public void setXsd2Java(Xsd2Java value) {
        this.xsd2Java = value;
    }

    /**
     * Gets the value of the xmlformat property.
     * 
     * @return
     *     possible object is
     *     {@link Xmlformat }
     *     
     */
    public Xmlformat getXmlformat() {
        return xmlformat;
    }

    /**
     * Sets the value of the xmlformat property.
     * 
     * @param value
     *     allowed object is
     *     {@link Xmlformat }
     *     
     */
    public void setXmlformat(Xmlformat value) {
        this.xmlformat = value;
    }

    /**
     * Gets the value of the build property.
     * 
     * @return
     *     possible object is
     *     {@link Build }
     *     
     */
    public Build getBuild() {
        return build;
    }

    /**
     * Sets the value of the build property.
     * 
     * @param value
     *     allowed object is
     *     {@link Build }
     *     
     */
    public void setBuild(Build value) {
        this.build = value;
    }

    /**
     * Gets the value of the javaformat property.
     * 
     * @return
     *     possible object is
     *     {@link Javaformat }
     *     
     */
    public Javaformat getJavaformat() {
        return javaformat;
    }

    /**
     * Sets the value of the javaformat property.
     * 
     * @param value
     *     allowed object is
     *     {@link Javaformat }
     *     
     */
    public void setJavaformat(Javaformat value) {
        this.javaformat = value;
    }

    /**
     * Gets the value of the exportCommitLog property.
     * 
     * @return
     *     possible object is
     *     {@link ExportCommitLog }
     *     
     */
    public ExportCommitLog getExportCommitLog() {
        return exportCommitLog;
    }

    /**
     * Sets the value of the exportCommitLog property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExportCommitLog }
     *     
     */
    public void setExportCommitLog(ExportCommitLog value) {
        this.exportCommitLog = value;
    }

}
