//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.01 at 09:17:57 AM CST 
//


package com.yuan.gui.app.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for exportCommitLog complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="exportCommitLog">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="choice" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="codePath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="srcFile" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="destFile" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="logConfig" type="{http://www.example.org/config}logConfig" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "exportCommitLog", propOrder = {
    "choice",
    "codePath",
    "srcFile",
    "destFile",
    "logConfig"
})
public class ExportCommitLog {

    @XmlElement(required = true)
    protected String choice;
    @XmlElement(required = true)
    protected String codePath;
    @XmlElement(required = true)
    protected String srcFile;
    @XmlElement(required = true)
    protected String destFile;
    protected LogConfig logConfig;

    /**
     * Gets the value of the choice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChoice() {
        return choice;
    }

    /**
     * Sets the value of the choice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChoice(String value) {
        this.choice = value;
    }

    /**
     * Gets the value of the codePath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodePath() {
        return codePath;
    }

    /**
     * Sets the value of the codePath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodePath(String value) {
        this.codePath = value;
    }

    /**
     * Gets the value of the srcFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrcFile() {
        return srcFile;
    }

    /**
     * Sets the value of the srcFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrcFile(String value) {
        this.srcFile = value;
    }

    /**
     * Gets the value of the destFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestFile() {
        return destFile;
    }

    /**
     * Sets the value of the destFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestFile(String value) {
        this.destFile = value;
    }

    /**
     * Gets the value of the logConfig property.
     * 
     * @return
     *     possible object is
     *     {@link LogConfig }
     *     
     */
    public LogConfig getLogConfig() {
        return logConfig;
    }

    /**
     * Sets the value of the logConfig property.
     * 
     * @param value
     *     allowed object is
     *     {@link LogConfig }
     *     
     */
    public void setLogConfig(LogConfig value) {
        this.logConfig = value;
    }

}
