//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.01 at 09:17:57 AM CST 
//


package com.yuan.gui.app.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for logConfig complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="logConfig">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="revision" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="svnAccounts" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="message" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="projectTeam" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="no" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="modifyReason" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="modifyDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="author" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="fileList" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "logConfig", propOrder = {
    "revision",
    "svnAccounts",
    "date",
    "message",
    "projectTeam",
    "no",
    "modifyReason",
    "modifyDesc",
    "author",
    "fileList"
})
public class LogConfig {

    @XmlElement(required = true)
    protected String revision;
    @XmlElement(required = true)
    protected String svnAccounts;
    @XmlElement(required = true)
    protected String date;
    @XmlElement(required = true)
    protected String message;
    @XmlElement(required = true)
    protected String projectTeam;
    @XmlElement(required = true)
    protected String no;
    @XmlElement(required = true)
    protected String modifyReason;
    @XmlElement(required = true)
    protected String modifyDesc;
    @XmlElement(required = true)
    protected String author;
    @XmlElement(required = true)
    protected String fileList;

    /**
     * Gets the value of the revision property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRevision() {
        return revision;
    }

    /**
     * Sets the value of the revision property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRevision(String value) {
        this.revision = value;
    }

    /**
     * Gets the value of the svnAccounts property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSvnAccounts() {
        return svnAccounts;
    }

    /**
     * Sets the value of the svnAccounts property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSvnAccounts(String value) {
        this.svnAccounts = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDate(String value) {
        this.date = value;
    }

    /**
     * Gets the value of the message property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessage() {
        return message;
    }

    /**
     * Sets the value of the message property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessage(String value) {
        this.message = value;
    }

    /**
     * Gets the value of the projectTeam property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProjectTeam() {
        return projectTeam;
    }

    /**
     * Sets the value of the projectTeam property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProjectTeam(String value) {
        this.projectTeam = value;
    }

    /**
     * Gets the value of the no property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNo() {
        return no;
    }

    /**
     * Sets the value of the no property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNo(String value) {
        this.no = value;
    }

    /**
     * Gets the value of the modifyReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModifyReason() {
        return modifyReason;
    }

    /**
     * Sets the value of the modifyReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModifyReason(String value) {
        this.modifyReason = value;
    }

    /**
     * Gets the value of the modifyDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModifyDesc() {
        return modifyDesc;
    }

    /**
     * Sets the value of the modifyDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModifyDesc(String value) {
        this.modifyDesc = value;
    }

    /**
     * Gets the value of the author property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthor() {
        return author;
    }

    /**
     * Sets the value of the author property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthor(String value) {
        this.author = value;
    }

    /**
     * Gets the value of the fileList property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileList() {
        return fileList;
    }

    /**
     * Sets the value of the fileList property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileList(String value) {
        this.fileList = value;
    }

}
