//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.01 at 09:17:57 AM CST 
//


package com.yuan.gui.app.schema;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.yuan.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.yuan.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Config }
     * 
     */
    public Config createConfig() {
        return new Config();
    }

    /**
     * Create an instance of {@link Settings }
     * 
     */
    public Settings createSettings() {
        return new Settings();
    }

    /**
     * Create an instance of {@link Xml2Xsd }
     * 
     */
    public Xml2Xsd createXml2Xsd() {
        return new Xml2Xsd();
    }

    /**
     * Create an instance of {@link Xsd2Java }
     * 
     */
    public Xsd2Java createXsd2Java() {
        return new Xsd2Java();
    }

    /**
     * Create an instance of {@link Xmlformat }
     * 
     */
    public Xmlformat createXmlformat() {
        return new Xmlformat();
    }

    /**
     * Create an instance of {@link Build }
     * 
     */
    public Build createBuild() {
        return new Build();
    }

    /**
     * Create an instance of {@link Javaformat }
     * 
     */
    public Javaformat createJavaformat() {
        return new Javaformat();
    }

    /**
     * Create an instance of {@link ExportCommitLog }
     * 
     */
    public ExportCommitLog createExportCommitLog() {
        return new ExportCommitLog();
    }

    /**
     * Create an instance of {@link LogConfig }
     * 
     */
    public LogConfig createLogConfig() {
        return new LogConfig();
    }

    /**
     * Create an instance of {@link MenuBar }
     * 
     */
    public MenuBar createMenuBar() {
        return new MenuBar();
    }

    /**
     * Create an instance of {@link Menu }
     * 
     */
    public Menu createMenu() {
        return new Menu();
    }

    /**
     * Create an instance of {@link MenuItem }
     * 
     */
    public MenuItem createMenuItem() {
        return new MenuItem();
    }

}
