//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.01 at 09:17:57 AM CST 
//


package com.yuan.gui.app.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for settings complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="settings">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="workDir" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="toolsDir" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="toolsSvnPath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="toolsSvnPathList" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="projectGroupDir" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="projectGroupList" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="codeDir" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="baseDir" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="baseDatabase" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="baseCodeDir" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="baseCodeSvnPath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="baseCodeSvnPathList" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="baseWorkSpaceDir" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="baseWorkSpaceSvnPath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="baseWorkSpaceSvnPathList" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="custDir" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="custWorkSpaceDir" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="custWorkSpaceSvnPath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="custWorkSpaceSvnPathList" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="beDir" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="beList" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="beDatabase" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="beCodeDir" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="beCodeSvnPath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="beCodeSvnPathList" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="docDir" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tnsnames" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tnsnamesList" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="tortoiseProcPath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tortoiseProcPathList" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="winRarPath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="winRarPathList" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="jdguiPath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="jdguiPathList" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "settings", propOrder = {
    "workDir",
    "toolsDir",
    "toolsSvnPath",
    "toolsSvnPathList",
    "projectGroupDir",
    "projectGroupList",
    "codeDir",
    "baseDir",
    "baseDatabase",
    "baseCodeDir",
    "baseCodeSvnPath",
    "baseCodeSvnPathList",
    "baseWorkSpaceDir",
    "baseWorkSpaceSvnPath",
    "baseWorkSpaceSvnPathList",
    "custDir",
    "custWorkSpaceDir",
    "custWorkSpaceSvnPath",
    "custWorkSpaceSvnPathList",
    "beDir",
    "beList",
    "beDatabase",
    "beCodeDir",
    "beCodeSvnPath",
    "beCodeSvnPathList",
    "docDir",
    "tnsnames",
    "tnsnamesList",
    "tortoiseProcPath",
    "tortoiseProcPathList",
    "winRarPath",
    "winRarPathList",
    "jdguiPath",
    "jdguiPathList"
})
public class Settings {

    @XmlElement(required = true)
    protected String workDir;
    @XmlElement(required = true)
    protected String toolsDir;
    @XmlElement(required = true)
    protected String toolsSvnPath;
    protected List<String> toolsSvnPathList;
    @XmlElement(required = true)
    protected String projectGroupDir;
    protected List<String> projectGroupList;
    @XmlElement(required = true)
    protected String codeDir;
    @XmlElement(required = true)
    protected String baseDir;
    @XmlElement(required = true)
    protected String baseDatabase;
    @XmlElement(required = true)
    protected String baseCodeDir;
    @XmlElement(required = true)
    protected String baseCodeSvnPath;
    protected List<String> baseCodeSvnPathList;
    @XmlElement(required = true)
    protected String baseWorkSpaceDir;
    @XmlElement(required = true)
    protected String baseWorkSpaceSvnPath;
    protected List<String> baseWorkSpaceSvnPathList;
    @XmlElement(required = true)
    protected String custDir;
    @XmlElement(required = true)
    protected String custWorkSpaceDir;
    @XmlElement(required = true)
    protected String custWorkSpaceSvnPath;
    protected List<String> custWorkSpaceSvnPathList;
    @XmlElement(required = true)
    protected String beDir;
    protected List<String> beList;
    @XmlElement(required = true)
    protected String beDatabase;
    @XmlElement(required = true)
    protected String beCodeDir;
    @XmlElement(required = true)
    protected String beCodeSvnPath;
    protected List<String> beCodeSvnPathList;
    @XmlElement(required = true)
    protected String docDir;
    @XmlElement(required = true)
    protected String tnsnames;
    protected List<String> tnsnamesList;
    @XmlElement(required = true)
    protected String tortoiseProcPath;
    protected List<String> tortoiseProcPathList;
    @XmlElement(required = true)
    protected String winRarPath;
    protected List<String> winRarPathList;
    @XmlElement(required = true)
    protected String jdguiPath;
    protected List<String> jdguiPathList;

    /**
     * Gets the value of the workDir property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWorkDir() {
        return workDir;
    }

    /**
     * Sets the value of the workDir property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWorkDir(String value) {
        this.workDir = value;
    }

    /**
     * Gets the value of the toolsDir property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToolsDir() {
        return toolsDir;
    }

    /**
     * Sets the value of the toolsDir property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToolsDir(String value) {
        this.toolsDir = value;
    }

    /**
     * Gets the value of the toolsSvnPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToolsSvnPath() {
        return toolsSvnPath;
    }

    /**
     * Sets the value of the toolsSvnPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToolsSvnPath(String value) {
        this.toolsSvnPath = value;
    }

    /**
     * Gets the value of the toolsSvnPathList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the toolsSvnPathList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getToolsSvnPathList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getToolsSvnPathList() {
        if (toolsSvnPathList == null) {
            toolsSvnPathList = new ArrayList<String>();
        }
        return this.toolsSvnPathList;
    }

    /**
     * Gets the value of the projectGroupDir property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProjectGroupDir() {
        return projectGroupDir;
    }

    /**
     * Sets the value of the projectGroupDir property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProjectGroupDir(String value) {
        this.projectGroupDir = value;
    }

    /**
     * Gets the value of the projectGroupList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the projectGroupList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProjectGroupList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getProjectGroupList() {
        if (projectGroupList == null) {
            projectGroupList = new ArrayList<String>();
        }
        return this.projectGroupList;
    }

    /**
     * Gets the value of the codeDir property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodeDir() {
        return codeDir;
    }

    /**
     * Sets the value of the codeDir property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodeDir(String value) {
        this.codeDir = value;
    }

    /**
     * Gets the value of the baseDir property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseDir() {
        return baseDir;
    }

    /**
     * Sets the value of the baseDir property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseDir(String value) {
        this.baseDir = value;
    }

    /**
     * Gets the value of the baseDatabase property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseDatabase() {
        return baseDatabase;
    }

    /**
     * Sets the value of the baseDatabase property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseDatabase(String value) {
        this.baseDatabase = value;
    }

    /**
     * Gets the value of the baseCodeDir property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseCodeDir() {
        return baseCodeDir;
    }

    /**
     * Sets the value of the baseCodeDir property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseCodeDir(String value) {
        this.baseCodeDir = value;
    }

    /**
     * Gets the value of the baseCodeSvnPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseCodeSvnPath() {
        return baseCodeSvnPath;
    }

    /**
     * Sets the value of the baseCodeSvnPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseCodeSvnPath(String value) {
        this.baseCodeSvnPath = value;
    }

    /**
     * Gets the value of the baseCodeSvnPathList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the baseCodeSvnPathList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBaseCodeSvnPathList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getBaseCodeSvnPathList() {
        if (baseCodeSvnPathList == null) {
            baseCodeSvnPathList = new ArrayList<String>();
        }
        return this.baseCodeSvnPathList;
    }

    /**
     * Gets the value of the baseWorkSpaceDir property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseWorkSpaceDir() {
        return baseWorkSpaceDir;
    }

    /**
     * Sets the value of the baseWorkSpaceDir property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseWorkSpaceDir(String value) {
        this.baseWorkSpaceDir = value;
    }

    /**
     * Gets the value of the baseWorkSpaceSvnPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseWorkSpaceSvnPath() {
        return baseWorkSpaceSvnPath;
    }

    /**
     * Sets the value of the baseWorkSpaceSvnPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseWorkSpaceSvnPath(String value) {
        this.baseWorkSpaceSvnPath = value;
    }

    /**
     * Gets the value of the baseWorkSpaceSvnPathList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the baseWorkSpaceSvnPathList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBaseWorkSpaceSvnPathList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getBaseWorkSpaceSvnPathList() {
        if (baseWorkSpaceSvnPathList == null) {
            baseWorkSpaceSvnPathList = new ArrayList<String>();
        }
        return this.baseWorkSpaceSvnPathList;
    }

    /**
     * Gets the value of the custDir property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustDir() {
        return custDir;
    }

    /**
     * Sets the value of the custDir property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustDir(String value) {
        this.custDir = value;
    }

    /**
     * Gets the value of the custWorkSpaceDir property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustWorkSpaceDir() {
        return custWorkSpaceDir;
    }

    /**
     * Sets the value of the custWorkSpaceDir property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustWorkSpaceDir(String value) {
        this.custWorkSpaceDir = value;
    }

    /**
     * Gets the value of the custWorkSpaceSvnPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustWorkSpaceSvnPath() {
        return custWorkSpaceSvnPath;
    }

    /**
     * Sets the value of the custWorkSpaceSvnPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustWorkSpaceSvnPath(String value) {
        this.custWorkSpaceSvnPath = value;
    }

    /**
     * Gets the value of the custWorkSpaceSvnPathList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the custWorkSpaceSvnPathList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCustWorkSpaceSvnPathList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getCustWorkSpaceSvnPathList() {
        if (custWorkSpaceSvnPathList == null) {
            custWorkSpaceSvnPathList = new ArrayList<String>();
        }
        return this.custWorkSpaceSvnPathList;
    }

    /**
     * Gets the value of the beDir property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBeDir() {
        return beDir;
    }

    /**
     * Sets the value of the beDir property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBeDir(String value) {
        this.beDir = value;
    }

    /**
     * Gets the value of the beList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the beList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBeList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getBeList() {
        if (beList == null) {
            beList = new ArrayList<String>();
        }
        return this.beList;
    }

    /**
     * Gets the value of the beDatabase property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBeDatabase() {
        return beDatabase;
    }

    /**
     * Sets the value of the beDatabase property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBeDatabase(String value) {
        this.beDatabase = value;
    }

    /**
     * Gets the value of the beCodeDir property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBeCodeDir() {
        return beCodeDir;
    }

    /**
     * Sets the value of the beCodeDir property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBeCodeDir(String value) {
        this.beCodeDir = value;
    }

    /**
     * Gets the value of the beCodeSvnPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBeCodeSvnPath() {
        return beCodeSvnPath;
    }

    /**
     * Sets the value of the beCodeSvnPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBeCodeSvnPath(String value) {
        this.beCodeSvnPath = value;
    }

    /**
     * Gets the value of the beCodeSvnPathList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the beCodeSvnPathList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBeCodeSvnPathList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getBeCodeSvnPathList() {
        if (beCodeSvnPathList == null) {
            beCodeSvnPathList = new ArrayList<String>();
        }
        return this.beCodeSvnPathList;
    }

    /**
     * Gets the value of the docDir property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocDir() {
        return docDir;
    }

    /**
     * Sets the value of the docDir property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocDir(String value) {
        this.docDir = value;
    }

    /**
     * Gets the value of the tnsnames property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTnsnames() {
        return tnsnames;
    }

    /**
     * Sets the value of the tnsnames property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTnsnames(String value) {
        this.tnsnames = value;
    }

    /**
     * Gets the value of the tnsnamesList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tnsnamesList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTnsnamesList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getTnsnamesList() {
        if (tnsnamesList == null) {
            tnsnamesList = new ArrayList<String>();
        }
        return this.tnsnamesList;
    }

    /**
     * Gets the value of the tortoiseProcPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTortoiseProcPath() {
        return tortoiseProcPath;
    }

    /**
     * Sets the value of the tortoiseProcPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTortoiseProcPath(String value) {
        this.tortoiseProcPath = value;
    }

    /**
     * Gets the value of the tortoiseProcPathList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tortoiseProcPathList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTortoiseProcPathList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getTortoiseProcPathList() {
        if (tortoiseProcPathList == null) {
            tortoiseProcPathList = new ArrayList<String>();
        }
        return this.tortoiseProcPathList;
    }

    /**
     * Gets the value of the winRarPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWinRarPath() {
        return winRarPath;
    }

    /**
     * Sets the value of the winRarPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWinRarPath(String value) {
        this.winRarPath = value;
    }

    /**
     * Gets the value of the winRarPathList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the winRarPathList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWinRarPathList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getWinRarPathList() {
        if (winRarPathList == null) {
            winRarPathList = new ArrayList<String>();
        }
        return this.winRarPathList;
    }

    /**
     * Gets the value of the jdguiPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJdguiPath() {
        return jdguiPath;
    }

    /**
     * Sets the value of the jdguiPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJdguiPath(String value) {
        this.jdguiPath = value;
    }

    /**
     * Gets the value of the jdguiPathList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the jdguiPathList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getJdguiPathList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getJdguiPathList() {
        if (jdguiPathList == null) {
            jdguiPathList = new ArrayList<String>();
        }
        return this.jdguiPathList;
    }

}
