//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.01 at 09:17:57 AM CST 
//


package com.yuan.gui.app.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for xml2xsd complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="xml2xsd">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="proxyhost" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="proxyport" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="proxyuser" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="proxypwd" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="toolpath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="xmlpath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="xsdpath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "xml2xsd", propOrder = {
    "proxyhost",
    "proxyport",
    "proxyuser",
    "proxypwd",
    "toolpath",
    "xmlpath",
    "xsdpath"
})
public class Xml2Xsd {

    @XmlElement(required = true)
    protected String proxyhost;
    @XmlElement(required = true)
    protected String proxyport;
    @XmlElement(required = true)
    protected String proxyuser;
    @XmlElement(required = true)
    protected String proxypwd;
    @XmlElement(required = true)
    protected String toolpath;
    @XmlElement(required = true)
    protected String xmlpath;
    @XmlElement(required = true)
    protected String xsdpath;

    /**
     * Gets the value of the proxyhost property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProxyhost() {
        return proxyhost;
    }

    /**
     * Sets the value of the proxyhost property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProxyhost(String value) {
        this.proxyhost = value;
    }

    /**
     * Gets the value of the proxyport property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProxyport() {
        return proxyport;
    }

    /**
     * Sets the value of the proxyport property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProxyport(String value) {
        this.proxyport = value;
    }

    /**
     * Gets the value of the proxyuser property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProxyuser() {
        return proxyuser;
    }

    /**
     * Sets the value of the proxyuser property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProxyuser(String value) {
        this.proxyuser = value;
    }

    /**
     * Gets the value of the proxypwd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProxypwd() {
        return proxypwd;
    }

    /**
     * Sets the value of the proxypwd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProxypwd(String value) {
        this.proxypwd = value;
    }

    /**
     * Gets the value of the toolpath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToolpath() {
        return toolpath;
    }

    /**
     * Sets the value of the toolpath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToolpath(String value) {
        this.toolpath = value;
    }

    /**
     * Gets the value of the xmlpath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXmlpath() {
        return xmlpath;
    }

    /**
     * Sets the value of the xmlpath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXmlpath(String value) {
        this.xmlpath = value;
    }

    /**
     * Gets the value of the xsdpath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXsdpath() {
        return xsdpath;
    }

    /**
     * Sets the value of the xsdpath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXsdpath(String value) {
        this.xsdpath = value;
    }

}
