//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.01 at 09:17:57 AM CST 
//


package com.yuan.gui.app.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for xsd2java complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="xsd2java">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="encoding" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="xsddir" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="javadir" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="package" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "xsd2java", propOrder = {
    "encoding",
    "xsddir",
    "javadir",
    "_package"
})
public class Xsd2Java {

    @XmlElement(required = true)
    protected String encoding;
    @XmlElement(required = true)
    protected String xsddir;
    @XmlElement(required = true)
    protected String javadir;
    @XmlElement(name = "package", required = true)
    protected String _package;

    /**
     * Gets the value of the encoding property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEncoding() {
        return encoding;
    }

    /**
     * Sets the value of the encoding property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEncoding(String value) {
        this.encoding = value;
    }

    /**
     * Gets the value of the xsddir property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXsddir() {
        return xsddir;
    }

    /**
     * Sets the value of the xsddir property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXsddir(String value) {
        this.xsddir = value;
    }

    /**
     * Gets the value of the javadir property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJavadir() {
        return javadir;
    }

    /**
     * Sets the value of the javadir property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJavadir(String value) {
        this.javadir = value;
    }

    /**
     * Gets the value of the package property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPackage() {
        return _package;
    }

    /**
     * Sets the value of the package property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPackage(String value) {
        this._package = value;
    }

}
